codigo-fonte/TrabalhoFinal/config/routes.rb
Rails.application.routes.draw do

  
  resources :orders
  
  devise_for :employees, 
              controllers: { registrations: 'employees/registrations' },
              path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  get 'pedido/fazerPedido'

  resources :products
  resources :categories
  resources :historics
  # get 'historics', to: 'historics#index'
  # get 'historics/:id', to: 'historics#show', as: :historic
  get 'categories', to: 'categories#index'
  get 'categories/new', to: 'categories#new', as: :new_company
  get 'categories/:id', to: 'categories#show', as: :company
  post 'categories', to: 'categories#create'

  root 'home#index'


  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

codigo-fonte/TrabalhoFinal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sistema de Gestão de Almoxarifado</title>
    <%= csrf_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <script>
  function teste() {
    window.location.reload();
  }
</script>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Sistema de Pedidos de Produtos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">

              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
              <% if employee_signed_in? %>

                <% if current_employee.admin?%>
                  <li class="nav-item">
                      <%= link_to 'Departamentos', departments_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'Produtos', products_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'Categorias', categories_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'Histórico', historics_path, class: 'nav-link' %>
                    </li>
                <% end %>
                <li class="nav-item">
                  <%= link_to 'Pedidos', orders_path, class: 'nav-link', id: 'pedidos',:onclick => 'teste()' %>
                </li>
              <% end %>
          </ul>

          <ul class="navbar-nav mr-0">
            <li class="nav-item">
              <% if employee_signed_in? %>
                <%= link_to "#{current_employee.name} (Deslogar)", destroy_employee_session_path, method: :delete, class: 'nav-link' %>
              <% else %>
                <%= link_to 'Login', new_employee_session_path, class: 'nav-link'  %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">

      <%= yield %>
    </div>
  </body>


</html>