codigo-fonte/TrabalhoFinal/config/routes.rb
Rails.application.routes.draw do

  
  resources :orders
  
  devise_for :employees, 
              controllers: { registrations: 'employees/registrations' },
              path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  get 'pedido/fazerPedido'

  resources :products
  resources :categories
  resources :historics
  # get 'historics', to: 'historics#index'
  # get 'historics/:id', to: 'historics#show', as: :historic
  get 'categories', to: 'categories#index'
  get 'categories/new', to: 'categories#new', as: :new_company
  get 'categories/:id', to: 'categories#show', as: :company
  post 'categories', to: 'categories#create'

  root 'home#index'


  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

codigo-fonte/TrabalhoFinal/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :employee
  belongs_to :product
end

codigo-fonte/TrabalhoFinal/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_employee!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index

    @orders = Order.where("status = 0 OR status = 3").where("employee_id = #{current_employee.id}")
    
    if current_employee.admin?
      @orders = Order.where("status = 3")
      render "indexAdm"
    end

  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    if current_employee.admin?
      render json: {status: "error", message: "Você não têm permissão Para acessar esta Página"}
    end 
  end

  # GET /orders/new
  def new
    if !current_employee.admin?
      @order = Order.new
    else
      render json: {status: "error", message: "Você não têm permissão Para acessar esta Página"}
    end         
  end

  # GET /orders/1/edit
  def edit
    if current_employee.admin?
      render json: {status: "error", message: "Você não têm permissão Para acessar esta Página"}
    end 
  end

  # POST /orders
  # POST /orders.json
  def create
  
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        flash[:sucess] = "O pedido realizado com sucesso."
        format.html { redirect_to @order}
        format.json { render :show, status: :created, location: @order }
      else
        flash[:sucess] = "Falha ao realizar pedido."
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json

  def update
    respond_to do |format|

      status = Integer(order_params[:status])
      id = @order.product.id
      produto = Product.find(id)
      quantidadeAtual = produto.quantity
      quantidadePedido = @order.quantity
      case status
        when 1

          if quantidadePedido < quantidadeAtual

            total = quantidadeAtual - quantidadePedido
            if atualizar_produto id, total
              time = Time.now
              usuario = Integer(current_employee.department.id)
              @historic = Historic.new(date: "2018-10-12", quantity: quantidadePedido, historic_type: "SAIDA" , product_id: id, employee_id: usuario)
              if @historic.save
                puts "saida Registrada#{time}"
              end
            end
            puts "status#{status}"
            puts "ID: #{id}"
            puts "Produto: #{quantidadeAtual}"
            puts "Pedido: #{quantidadePedido}"
            puts "Pedido: #{total}"
            if @order.update(order_params)
              flash[:sucess] = "O pedido foi atualizado com sucesso."
              format.html { redirect_to action: :index}
              format.json { render :show, status: :ok, location: @order }
            else

              format.html { render :show }
              format.json { render json: @order.errors, status: :unprocessable_entity }
            end
          else
            flash[:error] = "A quantidade solicitada excede a quantidade disponível."
            format.html { redirect_to action: :index}
          end
        else

          if @order.update(order_params)
            if status == 0
              flash[:sucess] = "O pedido foi recusado."
            elsif status == 3
              flash[:sucess] = "O pedido foi atualizado com sucesso."
            end
            
            format.html { redirect_to action: :index}
            format.json { render :show, status: :ok, location: @order }
          else
            flash[:error] = "O pedido não foi alterado."
            format.html { render :show }
            format.json { render json: @order.errors, status: :unprocessable_entity }
          end
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy  
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def atualizar_produto id, total
    Product.update(id, :quantity => total)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:status, :quantity, :employee_id, :product_id)
    end
end

codigo-fonte/TrabalhoFinal/app/helpers/orders_helper.rb
module OrdersHelper
end

codigo-fonte/TrabalhoFinal/app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">    
    <%= f.input :status, :as => :hidden, :input_html => { :value => "3" } %>
    <%= f.input :quantity, label:'Quantidade' %>
    <%= f.input :employee_id, :as => :hidden, :input_html => { :value => "#{current_employee.id}" }
 %>

    <%= f.association :product, label:'Produto' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

codigo-fonte/TrabalhoFinal/app/views/orders/edit.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @order, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Visualizar
  <% end %>
  <h1>Editar pedido</h1>
</div>

<%= render 'form' %>

codigo-fonte/TrabalhoFinal/app/views/orders/index.html.erb
<div class="page-header">
  <h1>Meus Pedidos</h1>
</div>
<% if flash[:error] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif flash[:sucess] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:sucess] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Funcionário</th>
        <th>Status</th>
        <% if !current_employee.admin? %>
        <th></th>
        <th></th>
        <th></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.product.name %></td>
          <td><%= order.quantity %></td>
          <td><%= order.employee.name %></td>
          <td>
            <%if order.status == 3%>
                Aguardando
            <%elsif order.status == 0 %>
                Recusado
            <%end %>
         </td>
          <% if !current_employee.admin? %>
            <td>
                <%= link_to 'visualizar', order, class: 'nav-link' %>
            </td>
            <td>
                <%= link_to 'Editar', edit_order_path(order) %>
            </td>
            <td>
                <%= link_to 'Deletar', order, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          <% end %>

        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to new_order_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Fazer Pedido
  <% end %>
</div>

codigo-fonte/TrabalhoFinal/app/views/orders/indexAdm.html.erb
<div class="page-header">
  <h1>Pedidos</h1>
</div>
<% if flash[:error] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>      
<% elsif flash[:sucess] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:sucess] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>      
<% end %>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Funcionário</th>        
        <th>Status</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.product.name %></td>
          <td><%= order.quantity %></td>
          <td><%= order.employee.name%> (<%=order.employee.department.name%>)</td>
          <td align="center">            
            <%if order.status == 3 %>
              <%= form_tag("/orders/#{order.id}", method: "patch",:id => 'form') do %>
                <input type = "hidden" id = "status" name = "order[status]" value = "0">              
                  
                  <i id="ap" class="fas fa-thumbs-up"></i>   
                  <i id="rp" class="fas fa-thumbs-down"></i>                                                     
              <% end %>                          
              <%= form_tag("/orders/#{order.id}", method: "patch") do %>

                  <input type = "hidden" id = "teste" name = "order[status]" value = "1">  
                                         
                  <% end %>                      
              <%end %>      
                 
         </td>                                
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

codigo-fonte/TrabalhoFinal/app/views/orders/new.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New order</h1>
</div>

<%= render 'form' %>

codigo-fonte/TrabalhoFinal/app/views/orders/show.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Pedido</h1>
</div>
<% if flash[:error] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>      
<% elsif flash[:sucess] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:sucess] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>      
<% end %>
<dl class="dl-horizontal">
  <dt>Status:</dt>
  <dd><% if @order.status== 3 %> Aguardando <% end %></dd>

  <dt>Quantidade:</dt>
  <dd><%= @order.quantity %></dd>

  <dt>Funcionário:</dt>
  <dd><%= @order.employee.name %></dd>

  <dt>Produto:</dt>
  <dd><%= @order.product.name %></dd>
</dl>
  <%= link_to edit_order_path(@order), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>